apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Aseel00/Polybot-infra.git
    targetRevision: HEAD
    path: tf/k8s/dev/ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: ingress-nginx-admission-patch
      namespace: ingress-nginx
    - group: batch
      kind: Job
      name: ingress-nginx-admission-create
      namespace: ingress-nginx