apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-dev
  name: yolo-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-dev
  template:
    metadata:
      labels:
        app: yolo-dev
    spec:
      containers:
      - env:
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: yolo-dev-secrets
                key: BUCKET_NAME
          - name: SQS_URL
            valueFrom:
              secretKeyRef:
                name: yolo-dev-secrets
                key: SQS_URL
          - name: REGION
            valueFrom:
              secretKeyRef:
                name: yolo-dev-secrets
                key: REGION
          - name: DDB_TABLE_NAME
            valueFrom:
              secretKeyRef:
                name: yolo-dev-secrets
                key: DDB_TABLE_NAME
          - name: STORAGE_TYPE
            valueFrom:
              secretKeyRef:
                name: yolo-dev-secrets
                key: STORAGE_TYPE
          - name:
            value: polybot-dev-service

        image: aseelarr/yolo-dev:latest
        name: yolo-container
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi