apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Aseel00/Polybot-infra.git
    targetRevision: HEAD
    path: tf/k8s/dev/YoloService
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
