name: Deploy Nginx to Dev

on:
  push:
    branches:
      - dev


jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2 (Dev)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx/conf.d/default.dev.conf ,deploy_nginx.sh"
          target: "/home/ubuntu/PolybotInfra"

      - name: Deploy to EC2 (Dev)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/PolybotInfra
            git pull origin dev
            mkdir -p /home/ubuntu/conf.d
            cp nginx_config/default_dev.conf /home/ubuntu/conf.d/default.conf
            ./deploy_nginx.sh
