name: Deploy Nginx Config to EC2

on:
  push:
    paths:
      - 'nginx-config/**'
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy Nginx config to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "nginx-config/default.conf"
        target: "/etc/nginx/conf.d/"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo nginx -t && sudo systemctl restart nginx
